DEPENDENCIES += lib_platform
DEPENDENCIES += lib_pugixml
DEPENDENCIES += lib_poly2tri
INCLUDEPATHS += lib_assimp/inc/
LIBRARIES    += lib_assimp

DEFINES += ASSIMP_BUILD_NO_OWN_ZLIB
DEFINES += ASSIMP_BUILD_NO_IFC_IMPORTER
DEFINES += ASSIMP_BUILD_NO_OPENGEX_IMPORTER
